parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"Ztkr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=require("react/jsx-runtime");function a(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}class s extends e.Component{constructor(...e){super(...e),a(this,"state",{active:0}),a(this,"handleIndexClick",e=>{this.setState({active:+e.target.dataset.index})})}render(){const{active:e}=this.state,{images:a}=this.props;return(0,t.jsxs)("div",{className:"carousel",children:[(0,t.jsx)("img",{src:a[e],alt:"animal"}),(0,t.jsx)("div",{className:"carousel-smaller",children:a.map((a,s)=>(0,t.jsx)("img",{src:a,"data-index":s,onClick:this.handleIndexClick,className:s===e?"active":"",alt:"animal thumbnail"},a))})]})}}a(s,"defaultProps",{images:["http://pets-v2.dev-apis.com/pets/none.jpg"]});var r=s;exports.default=r;
},{}],"D8Y6":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=n(require("react")),r=require("react-router-dom"),t=require("react/jsx-runtime");function o(e){if("function"!=typeof WeakMap)return null;var r=new WeakMap,t=new WeakMap;return(o=function(e){return e?t:r})(e)}function n(e,r){if(!r&&e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=o(r);if(t&&t.has(e))return t.get(e);var n={},i=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var a in e)if("default"!==a&&Object.prototype.hasOwnProperty.call(e,a)){var s=i?Object.getOwnPropertyDescriptor(e,a):null;s&&(s.get||s.set)?Object.defineProperty(n,a,s):n[a]=e[a]}return n.default=e,t&&t.set(e,n),n}function i(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}class a extends e.Component{constructor(...e){super(...e),i(this,"state",{hasError:!1,redirect:!1})}static getDerivedStateFromError(){return{hasError:!0}}componentDidCatch(e,r){console.error("ErrorBoundary caught an error",e,r),setTimeout(()=>{this.setState({redirect:!0})},5e3)}render(){return this.state.redirect?(0,t.jsx)(r.Redirect,{to:"/"}):this.state.hasError?(0,t.jsxs)("h2",{children:["This listing has an Error. ",(0,t.jsx)(r.Link,{to:"/",children:"Click here"})," to go back to the homepage or wait 5 second."]}):this.props.children}}var s=a;exports.default=s;
},{}],"2tnM":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["green",()=>{}]);var r=t;exports.default=r;
},{}],"KnKP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=({children:c})=>{u=u||document.getElementById("modal");const n=(0,e.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c}),n.current)};var n=c;exports.default=n;
},{}],"C/Dc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=u;var e=require("react"),t=require("react-router-dom"),s=a(require("./Carousel")),i=a(require("./ErrorBoudary")),r=a(require("./ThemeContext")),o=a(require("./Modal")),n=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}function d(e,t,s){return t in e?Object.defineProperty(e,t,{value:s,enumerable:!0,configurable:!0,writable:!0}):e[t]=s,e}class l extends e.Component{constructor(...e){super(...e),d(this,"state",{loading:!0}),d(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),d(this,"adopt",()=>{window.location="http://youtube.com"})}async componentDidMount(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}render(){const{showModal:e}=this.state;if(this.state.loading)return(0,n.jsx)("h2",{children:"Loading"});const{animal:t,breed:i,city:a,state:d,description:l,name:c,images:u}=this.state;return(0,n.jsxs)("div",{className:"details",children:[(0,n.jsx)(s.default,{images:u}),(0,n.jsxs)("div",{children:[(0,n.jsx)("h1",{children:c}),(0,n.jsx)("h2",{children:`${t} - ${i} - ${a}, ${d}`}),(0,n.jsx)(r.default.Consumer,{children:([e])=>(0,n.jsxs)("button",{onClick:this.toggleModal,style:{backgroundColor:e},children:["Adopt ",c]})}),(0,n.jsx)("p",{children:l}),e?(0,n.jsxs)(o.default,{children:[(0,n.jsxs)("div",{children:["Would you like adopt ",c,"?"]}),(0,n.jsxs)("div",{className:"buttons",children:[(0,n.jsx)("button",{onClick:this.adopt,children:"Yes"}),(0,n.jsx)("button",{onClick:this.toggleModal,children:"No"})]})]}):null]})]})}}const c=(0,t.withRouter)(l);function u(){return(0,n.jsx)(i.default,{children:(0,n.jsx)(c,{})})}
},{"./Carousel":"Ztkr","./ErrorBoudary":"D8Y6","./ThemeContext":"2tnM","./Modal":"KnKP"}],"/HkA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;var e=require("react");const t={};function a(a){const[s,n]=(0,e.useState)([]),[o,r]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?n[t[a]]:async function(){n([]),r("loading");const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${a}`),s=await e.json();t[a]=s.breeds||[],n(t[a]),r("loaded")}():n([])},[a]),[s,o]}
},{}],"qepC":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),s=require("react/jsx-runtime");const r=({name:r,animal:t,breed:i,images:a,location:n,id:l})=>{let c="http://pets-v2.dev-apis.com/pets/none.jpg";return a.length&&(c=a[0]),(0,s.jsxs)(e.Link,{to:`/details/${l}`,className:"pet",children:[(0,s.jsx)("div",{className:"image-container",children:(0,s.jsx)("img",{src:c,alt:t})}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("h1",{children:r}),(0,s.jsx)("h2",{children:`${t} - ${i} - ${n}`})]})]})};var t=r;exports.default=t;
},{}],"r5l1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("./Pet")),t=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}const r=({pets:a})=>(0,t.jsx)("div",{className:"search",children:a.length?a.map(a=>(0,t.jsx)(e.default,{animal:a.animal,name:a.name,breed:a.breed,images:a.images,location:`${a.city} , ${a.state}`,id:a.id},a.id)):(0,t.jsx)("h2",{children:"No pet found"})});var i=r;exports.default=i;
},{"./Pet":"qepC"}],"n0tu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=s(require("./useBreedList")),a=s(require("./Results")),r=s(require("./ThemeContext")),l=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}const o=["bird","cat","dog","rabbit","reptile"],n=()=>{const[s,n]=(0,e.useState)(""),[i,u]=(0,e.useState)(""),[c,d]=(0,e.useState)(""),[h,p]=(0,e.useState)([]),[x]=(0,t.default)(i),[v,j]=(0,e.useContext)(r.default);async function m(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${i}&location=${s}&breed=${c}`),t=await e.json();console.log(t),p(t.pets)}return(0,e.useEffect)(()=>{m()},[]),(0,l.jsxs)("div",{className:"search-params",children:[(0,l.jsxs)("form",{onSubmit:e=>{e.preventDefault(),m()},children:[(0,l.jsxs)("label",{htmlFor:"location",children:["Location",(0,l.jsx)("input",{id:"location",onChange:e=>n(e.target.value),value:s,placeholder:"Location"})]}),(0,l.jsxs)("label",{htmlFor:"animal",children:["Animal",(0,l.jsxs)("select",{id:"animal",value:i,onChange:e=>u(e.target.value),onBlur:e=>u(e.target.value),children:[(0,l.jsx)("option",{}),o.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsxs)("label",{htmlFor:"breed",children:["Breed",(0,l.jsxs)("select",{id:"breed",value:c,onChange:e=>d(e.target.value),onBlur:e=>d(e.target.value),children:[(0,l.jsx)("option",{}),x.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsx)("button",{style:{backgroundColor:v},children:"Submit"})]}),(0,l.jsx)(a.default,{pets:h})]})};var i=n;exports.default=i;
},{"./useBreedList":"/HkA","./Results":"r5l1","./ThemeContext":"2tnM"}],"eBcb":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=u(require("./Details")),d=u(require("./SearchParams")),i=u(require("./ThemeContext")),s=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const a=()=>{const u=(0,e.useState)("darkblue");return(0,s.jsx)(e.StrictMode,{children:(0,s.jsx)(i.default.Provider,{value:u,children:(0,s.jsxs)("div",{children:[(0,s.jsx)("header",{children:(0,s.jsx)(r.Link,{to:"/",children:"Adopt Me!"})}),(0,s.jsxs)(r.Switch,{children:[(0,s.jsx)(r.Route,{path:"/details/:id",children:(0,s.jsx)(t.default,{})}),(0,s.jsx)(r.Route,{path:"/",children:(0,s.jsx)(d.default,{})})]})]})})})};var l=a;exports.default=l;
},{"./Details":"C/Dc","./SearchParams":"n0tu","./ThemeContext":"2tnM"}],"Focm":[function(require,module,exports) {
"use strict";var e=o(require("express")),t=require("react-dom/server"),r=require("react-router-dom"),s=o(require("fs")),n=o(require("../src/App")),i=require("react/jsx-runtime");function o(e){return e&&e.__esModule?e:{default:e}}const u=process.env.PORT||3e3,d=s.default.readFileSync("dist/index.html").toString(),l=d.split("not rendered"),c=(0,e.default)();c.use("/dist",e.default.static("dist")),c.use((e,s)=>{s.write(l[0]);const o={};console.log("@@@");const u=(0,i.jsx)(r.StaticRouter,{url:e.url,context:o,children:(0,i.jsx)(n.default,{})}),d=(0,t.renderToNodeStream)(u);d.pipe(s,{end:!1}),d.on("end",()=>{s.status(o||200),s.write(l[1]),s.end()})}),console.log(`listening on http://localhost:${u}`),c.listen(u);
},{"../src/App":"eBcb"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map